#-------------------- guisheng ------------------------
guisheng:
    build: .
    env_file:
        - guisheng.env
    command: uwsgi --http 0.0.0.0:5432 --wsgi-file wsgi.py --callable app --processes 1 --threads 2
    ports:
        - "5432:5432"
    links:
        - redis1

#------------------- celery ---------------------------
celery:
    build: .
    env_file:
        - guisheng.env
    command: celery worker -A guisheng_app.workers.hottag.celery --loglevel=INFO
    links:
        - redis1

#------------------- celery beats----------------------
celery_beats:
    build: .
    env_file:
        - guisheng.env
    command: celery -A guisheng_app.workers.hottag.celery beat --loglevel=INFO
    links:
        - redis1

#------------------ redis ----------------------------
redis1:     #储存热门搜索
    image: redis
    command: redis-server --port 6380
    ports:
        - "6380:6380"
