#-------------------- guisheng ------------------------
guisheng:
    build: .
    env_file:
        - guisheng.env
    command: python wsgi.py runserver
    ports:
        - "8888:8888"
    links:
        - redis1

#------------------- celery ---------------------------
celery:
    build: .
    env_file:
        - guisheng.env
    command: celery worker -A guisheng_app.workers.hottag.celery --loglevel=info
    links:
        - redis1

#------------------- celery beats----------------------
celery_beats:
    build: .
    env_file:
        - guisheng.env
    command: celery -A guisheng_app.workers.hottag.celery beat --loglevel=INFO
    links:
        - redis1

#------------------ redis ----------------------------
redis1:     #储存热门搜索
    image: redis
    command: redis-server --port 6380
    ports:
        - "7380:6380"
